/**
 * Migration: 001_create_user_schema
 * 
 * Creates the User collection and schema with baseline indexes.
 * Maps to OpenAPI UserAccount schema (D1 User Accounts data store).
 * 
 * OpenAPI UserAccount fields (docs/apispecs2.1.yaml, line 48+):
 *   - userId: String (system-generated unique identifier, e.g., "usr_8f3d2a")
 *   - email: String, email format (required, unique, lowercase)
 *   - role: String, enum [student, professor, admin, coordinator, system] (default: student)
 *   - githubUsername: String (optional, linked by process 1.3)
 *   - emailVerified: Boolean (default: false)
 *   - accountStatus: String, enum [pending, active, suspended] (default: pending)
 *   - createdAt: DateTime (auto-generated by timestamps)
 * 
 * Implementation fields (not in spec but needed for functionality):
 *   - hashedPassword: String (required for local auth)
 *   - githubId: String (OAuth identifier)
 *   - studentId: String (linked to student ID registry)
 *   - lastLogin: Date
 *   - loginAttempts, lockedUntil, emailVerificationToken, passwordResetToken (security)
 *   - updatedAt: Date (auto-generated by timestamps)
 */

module.exports = {
  name: '001_create_user_schema',

  /**
   * Apply migration: Create User collection with schema and indexes
   * Idempotent: Safe to run multiple times (checks if collection exists)
   */
  up: async (db) => {
    try {
      const collections = await db.connection.db.listCollections({ name: 'users' }).toArray();

      if (collections.length > 0) {
        console.log('[MIGRATION] User collection already exists, skipping creation');
        return;
      }

      await db.connection.db.createCollection('users');
      console.log('[MIGRATION] Created User collection');
    } catch (error) {
      console.error('[MIGRATION] Error in 001_create_user_schema up:', error);
      throw error;
    }
  },

  /**
   * Rollback migration: Drop User collection
   * WARNING: Destructive operation - deletes all user data
   */
  down: async (db) => {
    try {
      // Check if User collection exists
      const User = db.model('User');
      if (User) {
        await User.collection.drop();
        console.log('[MIGRATION] Dropped User collection');
      }
    } catch (error) {
      // Collection doesn't exist or already deleted
      if (error.code === 26 || error.message.includes('ns not found')) {
        console.log('[MIGRATION] User collection does not exist, skipping drop');
        return;
      }
      console.error('[MIGRATION] Error in 001_create_user_schema down:', error);
      throw error;
    }
  },
};
