/**
 * Migration: 003_create_group_schema
 *
 * Creates the D2 data store: Group and GroupMembership collections with
 * all required indexes for the Group Formation process (DFD Process 2.x).
 *
 * D2 Group schema fields (docs/apispec2_2.yaml, components/schemas/GroupResponse):
 *   - groupId:       String (system-generated unique identifier, e.g., "grp_8f3d2a")
 *   - groupName:     String (required, unique, trimmed)
 *   - leaderId:      String (required, references D1 User)
 *   - advisorId:     String (nullable, references professor User)
 *   - status:        String, enum [pending_validation, active, inactive, archived]
 *   - members:       Array of embedded member objects (userId, role, status, joinedAt)
 *   - githubOrg:     String (nullable, set by Process 2.6)
 *   - githubRepoUrl: String (nullable, set by Process 2.6 — org-level repo URL)
 *   - jiraProjectKey / projectKey: String (nullable, set by Process 2.7)
 *   - jiraBoardUrl:  String (nullable, set by Process 2.7 — derived board URL)
 *   - createdAt:     DateTime (auto-generated by timestamps)
 *   - updatedAt:     DateTime (auto-generated by timestamps)
 *
 * D2 GroupMembership schema fields:
 *   - membershipId:  String (unique, auto-generated: mem_xxxxx)
 *   - groupId:       String (references Group)
 *   - studentId:     String (references D1 User)
 *   - status:        String, enum [pending, approved, rejected]
 *   - decidedBy:     String (nullable)
 *   - decidedAt:     Date (nullable)
 *   - createdAt / updatedAt: auto-generated
 *
 * Index strategy (per issue #44 acceptance criteria):
 *   groups:           groupId (unique PK), leaderId, status
 *   groupmemberships: (groupId, studentId) composite unique, (groupId, status)
 *
 * DFD flows covered:
 *   f18 — 2.2 → D2  (group record creation, createGroup controller)
 *   f19 — 2.4 → D2  (pending/approved/rejected member records, addMember + membershipDecision)
 *   f20 — D2  → 2.5 (read group members, getMembers)
 *   f21 — 2.8 → D2  (coordinator override updates, coordinatorOverride)
 *   f32 — D2  → 2.3 (read group data, getGroup)
 */

module.exports = {
  name: '003_create_group_schema',

  /**
   * Apply migration: Create groups and groupmemberships collections with indexes.
   * Idempotent: safe to run multiple times (checks existence before creating).
   */
  up: async (db) => {
    const conn = db.connection.db;

    // --- groups collection ---
    const groupCollections = await conn.listCollections({ name: 'groups' }).toArray();
    if (groupCollections.length === 0) {
      await conn.createCollection('groups');
      console.log('[MIGRATION] Created groups collection');
    } else {
      console.log('[MIGRATION] groups collection already exists, skipping creation');
    }

    const groupsColl = conn.collection('groups');

    // groupId unique index (logical PK — Mongoose also enforces this via schema)
    await groupsColl.createIndex({ groupId: 1 }, { unique: true });
    console.log('[MIGRATION] Ensured index: groups.groupId (unique)');

    // leaderId index — supports queries like "find all groups led by student X"
    await groupsColl.createIndex({ leaderId: 1 });
    console.log('[MIGRATION] Ensured index: groups.leaderId');

    // status index — supports filtering by pending_validation / active / inactive / archived
    await groupsColl.createIndex({ status: 1 });
    console.log('[MIGRATION] Ensured index: groups.status');

    // --- groupmemberships collection ---
    const membershipCollections = await conn.listCollections({ name: 'groupmemberships' }).toArray();
    if (membershipCollections.length === 0) {
      await conn.createCollection('groupmemberships');
      console.log('[MIGRATION] Created groupmemberships collection');
    } else {
      console.log('[MIGRATION] groupmemberships collection already exists, skipping creation');
    }

    const membershipsColl = conn.collection('groupmemberships');

    // Composite unique — a student can have at most one membership record per group (D2 upsert target)
    await membershipsColl.createIndex({ groupId: 1, studentId: 1 }, { unique: true });
    console.log('[MIGRATION] Ensured index: groupmemberships.(groupId, studentId) (unique)');

    // (groupId, status) — supports queries like "fetch all approved members for group X"
    await membershipsColl.createIndex({ groupId: 1, status: 1 });
    console.log('[MIGRATION] Ensured index: groupmemberships.(groupId, status)');
  },

  /**
   * Rollback migration: Drop groups and groupmemberships collections.
   * WARNING: Destructive — deletes all group and membership data.
   */
  down: async (db) => {
    const conn = db.connection.db;

    for (const collName of ['groups', 'groupmemberships']) {
      try {
        const exists = await conn.listCollections({ name: collName }).toArray();
        if (exists.length > 0) {
          await conn.collection(collName).drop();
          console.log(`[MIGRATION] Dropped ${collName} collection`);
        } else {
          console.log(`[MIGRATION] ${collName} collection does not exist, skipping drop`);
        }
      } catch (error) {
        if (error.code === 26 || error.message.includes('ns not found')) {
          console.log(`[MIGRATION] ${collName} collection does not exist, skipping drop`);
        } else {
          console.error(`[MIGRATION] Error dropping ${collName}:`, error);
          throw error;
        }
      }
    }
  },
};
