/**
 * Migration: 006_create_deliverable_schema
 *
 * Creates the Deliverable collection (D4) for storing student deliverable submissions.
 * Maps to Process 4.5 and Issue #76 (Deliverable Submission).
 *
 * D4 schema (Deliverable model):
 *   - deliverableId: String (unique, auto-generated, e.g., "dlv_abc123")
 *   - committeeId: String (reference to D3 Committee)
 *   - groupId: String (reference to D2 Group)
 *   - studentId: String (reference to D1 User)
 *   - type: String enum (proposal, statement_of_work, demonstration)
 *   - submittedAt: Date
 *   - storageRef: String (URL or file path)
 *   - format: String enum (document, link, file)
 *   - version: Number (default 1, increments on re-submission)
 *   - status: String enum (submitted, accepted, rejected)
 *   - createdAt, updatedAt: Date (auto-generated by timestamps)
 *
 * Indexes:
 *   - deliverableId (PK, unique)
 *   - committeeId + groupId (query by committee and group)
 *   - committeeId + type (query by committee and deliverable type)
 *   - groupId + submittedAt (timeline queries)
 *   - studentId + committeeId (student-specific queries)
 */

module.exports = {
  name: '006_create_deliverable_schema',

  /**
   * Apply migration: Create Deliverable collection with schema and indexes
   * Idempotent: Safe to run multiple times
   */
  up: async (db) => {
    try {
      const collections = await db.connection.db.listCollections({ name: 'deliverables' }).toArray();

      if (collections.length > 0) {
        console.log('[MIGRATION] Deliverable collection already exists, skipping creation');
        return;
      }

      await db.connection.db.createCollection('deliverables');
      console.log('[MIGRATION] Created Deliverable collection');

      // Create indexes
      const deliverableCollection = db.connection.db.collection('deliverables');

      await deliverableCollection.createIndex({ deliverableId: 1 }, { unique: true });
      console.log('[MIGRATION] Created index: deliverableId (unique)');

      await deliverableCollection.createIndex({ committeeId: 1, groupId: 1 });
      console.log('[MIGRATION] Created index: committeeId + groupId');

      await deliverableCollection.createIndex({ committeeId: 1, type: 1 });
      console.log('[MIGRATION] Created index: committeeId + type');

      await deliverableCollection.createIndex({ groupId: 1, submittedAt: -1 });
      console.log('[MIGRATION] Created index: groupId + submittedAt');

      await deliverableCollection.createIndex({ studentId: 1, committeeId: 1 });
      console.log('[MIGRATION] Created index: studentId + committeeId');
    } catch (error) {
      console.error('[MIGRATION] Error in 006_create_deliverable_schema up:', error);
      throw error;
    }
  },

  /**
   * Rollback migration: Drop Deliverable collection
   * Idempotent: Safe to run multiple times
   */
  down: async (db) => {
    try {
      const collections = await db.connection.db.listCollections({ name: 'deliverables' }).toArray();

      if (collections.length === 0) {
        console.log('[MIGRATION] Deliverable collection does not exist, skipping drop');
        return;
      }

      await db.connection.db.dropCollection('deliverables');
      console.log('[MIGRATION] Dropped Deliverable collection');
    } catch (error) {
      console.error('[MIGRATION] Error in 006_create_deliverable_schema down:', error);
      throw error;
    }
  },
};
