/**
 * Migration: 007_create_committee_schema
 *
 * Creates the Committee collection (D3) for storing committee assignments.
 * Maps to Process 4.0 (Committee Assignment workflow).
 *
 * D3 schema (Committee model):
 *   - committeeId: String (unique, auto-generated, e.g., "com_abc123")
 *   - committeeName: String (unique, required)
 *   - description: String (optional)
 *   - advisorIds: String[] (array of advisor/professor IDs)
 *   - juryIds: String[] (array of jury member IDs)
 *   - status: String enum (draft, validated, published)
 *   - createdBy: String (coordinator ID)
 *   - publishedAt: Date (null until published)
 *   - publishedBy: String (coordinator ID who published)
 *   - createdAt, updatedAt: Date (auto-generated by timestamps)
 *
 * Indexes:
 *   - committeeId (PK, unique)
 *   - committeeName (unique, for duplicate check)
 *   - status (filter by draft/published)
 *   - createdBy + status (coordinator's committees)
 */

module.exports = {
  name: '007_create_committee_schema',

  /**
   * Apply migration: Create Committee collection with schema and indexes
   * Idempotent: Safe to run multiple times
   */
  up: async (db) => {
    try {
      const collections = await db.connection.db.listCollections({ name: 'committees' }).toArray();

      if (collections.length > 0) {
        console.log('[MIGRATION] Committee collection already exists, skipping creation');
        return;
      }

      await db.connection.db.createCollection('committees');
      console.log('[MIGRATION] Created Committee collection');

      // Create indexes
      const committeeCollection = db.connection.db.collection('committees');

      await committeeCollection.createIndex({ committeeId: 1 }, { unique: true });
      console.log('[MIGRATION] Created index: committeeId (unique)');

      await committeeCollection.createIndex({ committeeName: 1 }, { unique: true });
      console.log('[MIGRATION] Created index: committeeName (unique)');

      await committeeCollection.createIndex({ status: 1 });
      console.log('[MIGRATION] Created index: status');

      await committeeCollection.createIndex({ createdBy: 1, status: 1 });
      console.log('[MIGRATION] Created index: createdBy + status');
    } catch (error) {
      console.error('[MIGRATION] Error in 007_create_committee_schema up:', error);
      throw error;
    }
  },

  /**
   * Rollback migration: Drop Committee collection
   * Idempotent: Safe to run multiple times
   */
  down: async (db) => {
    try {
      const collections = await db.connection.db.listCollections({ name: 'committees' }).toArray();

      if (collections.length === 0) {
        console.log('[MIGRATION] Committee collection does not exist, skipping drop');
        return;
      }

      await db.connection.db.dropCollection('committees');
      console.log('[MIGRATION] Dropped Committee collection');
    } catch (error) {
      console.error('[MIGRATION] Error in 007_create_committee_schema down:', error);
      throw error;
    }
  },
};
