/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * ISSUE #80 FIX #6: MIGRATION IDEMPOTENCY - INDEX CREATION GUARANTEE
 * ═══════════════════════════════════════════════════════════════════════════════
 * 
 * FILE: backend/migrations/007_create_committee_schema.js (DÜZELTILDI)
 * STATUS: ✅ MODIFIED
 * 
 * PROBLEM FIXED:
 * PR Review Issue #80 identified MIGRATION IDEMPOTENCY WEAKNESS. The original
 * migration script had this logic:
 *   IF collection doesn't exist → create collection → create indices
 *   ELSE → skip everything
 * 
 * This meant that in partially initialized environments:
 *   • Collection might exist without proper indices
 *   • Race conditions could occur without unique constraints
 *   • Compound indices might not be created
 *   • Data consistency could not be guaranteed
 * 
 * WHAT CHANGED:
 * • Separated collection creation from index creation
 * • Always attempt to create/ensure indices regardless of collection state
 * • MongoDB's createIndex is idempotent: safe to call multiple times
 * • Indices guaranteed to exist after migration runs
 * 
 * BEFORE (BROKEN):
 * ❌ if (collections.length > 0) {
 *      console.log('Collection exists, skipping');
 *      return;  // 🔴 INDICES NOT CREATED!
 *    }
 *    // Only reach this if collection doesn't exist
 *    createIndex(...);
 * 
 * AFTER (FIXED):
 * ✅ if (collections.length === 0) {
 *      create collection
 *    }
 *    // ALWAYS run index creation
 *    createIndex(committeeId);
 *    createIndex(committeeName);
 *    createIndex(createdBy + committeeName);  // NEW compound index
 *    // All indices now guaranteed to exist
 * 
 * MIGRATION: 007_create_committee_schema
 *
 * Creates the Committee collection (D3) for storing committee assignments.
 * Maps to Process 4.0 (Committee Assignment workflow).
 *
 * D3 schema (Committee model):
 *   - committeeId: String (unique, auto-generated, e.g., "com_abc123")
 *   - committeeName: String (unique, required)
 *   - description: String (optional)
 *   - advisorIds: String[] (array of advisor/professor IDs)
 *   - juryIds: String[] (array of jury member IDs)
 *   - status: String enum (draft, validated, published)
 *   - createdBy: String (coordinator ID)
 *   - publishedAt: Date (null until published)
 *   - publishedBy: String (coordinator ID who published)
 *   - createdAt, updatedAt: Date (auto-generated by timestamps)
 *
 * Indexes Created:
 *   - committeeId (PK, unique)
 *   - committeeName (unique, for duplicate check)
 *   - status (filter by draft/published)
 *   - createdBy + status (coordinator's committees)
 *   - createdBy + committeeName (NEW: compound unique per coordinator)
 * ═══════════════════════════════════════════════════════════════════════════════
 */

module.exports = {
  name: '007_create_committee_schema',

  /**
   * Apply migration: Create Committee collection with schema and indexes
   * FIXED: Now ensures indices are created even if collection already exists

   * Idempotent: Safe to run multiple times
   */
  up: async (db) => {
    try {
      const collections = await db.connection.db.listCollections({ name: 'committees' }).toArray();

      if (collections.length === 0) {
        await db.connection.db.createCollection('committees');
        console.log('[MIGRATION] Created Committee collection');
      } else {
        console.log('[MIGRATION] Committee collection already exists, skipping creation');
      }

      /**
       * =====================================================================
       * FIX #5: ENSURE INDICES CREATED EVEN IF COLLECTION EXISTS (ISSUE #80 - MEDIUM)
       * =====================================================================
       * PROBLEM: Migration scripts skip index creation if collection already exists.
       * In partially initialized environments, required indices may never be created,
       * leading to:
       * - Duplicate records bypass uniqueness checks
       * - Inefficient queries without compound indices
       * - Race conditions in concurrent writes
       *
       * SOLUTION: Separate collection existence check from index creation.
       * Always create/ensure indices regardless of collection state.
       * MongoDB's createIndex is idempotent - safe to call multiple times.
       *
       * IMPACT: Indices are guaranteed to exist after migration runs,
       * ensuring data integrity and query performance.
       * =====================================================================
       */
      const committeeCollection = db.connection.db.collection('committees');

      // Always create indices - MongoDB handles duplicates gracefully
      await committeeCollection.createIndex({ committeeId: 1 }, { unique: true });
      console.log('[MIGRATION] Ensured index: committeeId (unique)');

      await committeeCollection.createIndex({ committeeName: 1 }, { unique: true });
      console.log('[MIGRATION] Ensured index: committeeName (unique)');

      // FIX #3 (from Committee model): Add compound unique index
      await committeeCollection.createIndex({ createdBy: 1, committeeName: 1 }, { unique: true });
      console.log('[MIGRATION] Ensured index: createdBy + committeeName (unique)');

      await committeeCollection.createIndex({ status: 1 });
      console.log('[MIGRATION] Ensured index: status');

      await committeeCollection.createIndex({ createdBy: 1, status: 1 });
      console.log('[MIGRATION] Ensured index: createdBy + status');
    } catch (error) {
      console.error('[MIGRATION] Error in 007_create_committee_schema up:', error);
      throw error;
    }
  },

  /**
   * Rollback migration: Drop Committee collection
   * Idempotent: Safe to run multiple times
   */
  down: async (db) => {
    try {
      const collections = await db.connection.db.listCollections({ name: 'committees' }).toArray();

      if (collections.length === 0) {
        console.log('[MIGRATION] Committee collection does not exist, skipping drop');
        return;
      }

      await db.connection.db.dropCollection('committees');
      console.log('[MIGRATION] Dropped Committee collection');
    } catch (error) {
      console.error('[MIGRATION] Error in 007_create_committee_schema down:', error);
      throw error;
    }
  },
};
