/**
 * Migration: 008_create_d6_sprint_and_contribution_schema
 *
 * Creates the SprintRecord and ContributionRecord collections (D6) for sprint tracking
 * and contribution calculation. Maps to Process 4.5 and Process 7.0.
 *
 * D6 - SprintRecord schema:
 *   - sprintRecordId: String (unique, auto-generated, e.g., "spr_abc123")
 *   - sprintId: String (reference to sprint configuration)
 *   - groupId: String (reference to D2 Group)
 *   - committeeId: String (reference to D3 Committee, null until published)
 *   - committeeAssignedAt: Date (timestamp when committee assigned, flow f13)
 *   - deliverableRefs: Array of {deliverableId, type, submittedAt} (cross-references to D4)
 *   - status: String enum (pending, in_progress, submitted, reviewed, completed)
 *   - createdAt, updatedAt: Date (auto-generated by timestamps)
 *
 * D6 - ContributionRecord schema:
 *   - contributionRecordId: String (unique, auto-generated, e.g., "ctr_abc123")
 *   - sprintId: String (reference to sprint)
 *   - studentId: String (reference to D1 User)
 *   - groupId: String (reference to D2 Group)
 *   - storyPointsAssigned: Number (from JIRA)
 *   - storyPointsCompleted: Number (calculated from PR merges)
 *   - pullRequestsMerged: Number (from GitHub)
 *   - issuesResolved: Number (from GitHub/JIRA)
 *   - commitsCount: Number (from GitHub)
 *   - contributionRatio: Number (0-1, storyPointsCompleted / storyPointsAssigned)
 *   - gitHubHandle: String (for GitHub API queries)
 *   - lastUpdatedAt: Date (timestamp of last GitHub sync)
 *   - createdAt, updatedAt: Date (auto-generated by timestamps)
 *
 * Indexes:
 *   SprintRecord:
 *     - sprintRecordId (PK, unique)
 *     - sprintId + groupId (primary query)
 *     - committeeId + sprintId (committee view)
 *     - groupId + status (group status tracking)
 *
 *   ContributionRecord:
 *     - contributionRecordId (PK, unique)
 *     - sprintId + studentId + groupId (primary query)
 *     - sprintId + groupId (sprint aggregate)
 *     - studentId + sprintId (student performance)
 */

module.exports = {
  name: '008_create_d6_sprint_and_contribution_schema',

  /**
   * Apply migration: Create SprintRecord and ContributionRecord collections
   * Idempotent: Safe to run multiple times
   */
  up: async (db) => {
    try {
      // Create SprintRecord collection
      const sprintCollections = await db.connection.db.listCollections({ name: 'sprintrecords' }).toArray();

      if (sprintCollections.length === 0) {
        await db.connection.db.createCollection('sprintrecords');
        console.log('[MIGRATION] Created SprintRecord collection');
      } else {
        console.log('[MIGRATION] SprintRecord collection already exists, skipping creation');
      }

      const sprintRecordCollection = db.connection.db.collection('sprintrecords');

      await sprintRecordCollection.createIndex({ sprintRecordId: 1 }, { unique: true });
      console.log('[MIGRATION] Created/synced index: sprintRecordId (unique)');

      await sprintRecordCollection.createIndex({ sprintId: 1, groupId: 1 }, { unique: true });
      console.log('[MIGRATION] Created/synced index: sprintId + groupId (unique)');

      await sprintRecordCollection.createIndex({ committeeId: 1, sprintId: 1 });
      console.log('[MIGRATION] Created/synced index: committeeId + sprintId');

      await sprintRecordCollection.createIndex({ groupId: 1, status: 1 });
      console.log('[MIGRATION] Created/synced index: groupId + status');

      // Create ContributionRecord collection
      const contributionCollections = await db.connection.db.listCollections({ name: 'contributionrecords' }).toArray();

      if (contributionCollections.length === 0) {
        await db.connection.db.createCollection('contributionrecords');
        console.log('[MIGRATION] Created ContributionRecord collection');
      } else {
        console.log('[MIGRATION] ContributionRecord collection already exists, skipping creation');
      }

      const contributionRecordCollection = db.connection.db.collection('contributionrecords');

      await contributionRecordCollection.createIndex(
        { contributionRecordId: 1 },
        { unique: true }
      );
      console.log('[MIGRATION] Created/synced index: contributionRecordId (unique)');

      await contributionRecordCollection.createIndex({
        sprintId: 1,
        studentId: 1,
        groupId: 1,
      }, { unique: true });
      console.log('[MIGRATION] Created/synced index: sprintId + studentId + groupId (unique)');

      await contributionRecordCollection.createIndex({ sprintId: 1, groupId: 1 });
      console.log('[MIGRATION] Created/synced index: sprintId + groupId');

      await contributionRecordCollection.createIndex({ studentId: 1, sprintId: 1 });
      console.log('[MIGRATION] Created/synced index: studentId + sprintId');
    } catch (error) {
      console.error('[MIGRATION] Error in 008_create_d6_sprint_and_contribution_schema up:', error);
      throw error;
    }
  },

  /**
   * Rollback migration: Drop SprintRecord and ContributionRecord collections
   * Idempotent: Safe to run multiple times
   */
  down: async (db) => {
    try {
      // Drop SprintRecord collection
      const sprintCollections = await db.connection.db.listCollections({ name: 'sprintrecords' }).toArray();

      if (sprintCollections.length > 0) {
        await db.connection.db.dropCollection('sprintrecords');
        console.log('[MIGRATION] Dropped SprintRecord collection');
      } else {
        console.log('[MIGRATION] SprintRecord collection does not exist, skipping drop');
      }

      // Drop ContributionRecord collection
      const contributionCollections = await db.connection.db.listCollections({ name: 'contributionrecords' }).toArray();

      if (contributionCollections.length > 0) {
        await db.connection.db.dropCollection('contributionrecords');
        console.log('[MIGRATION] Dropped ContributionRecord collection');
      } else {
        console.log('[MIGRATION] ContributionRecord collection does not exist, skipping drop');
      }
    } catch (error) {
      console.error('[MIGRATION] Error in 008_create_d6_sprint_and_contribution_schema down:', error);
      throw error;
    }
  },
};
